### PR TITLE
Finished Flask Application to be able to conform to new trained ML Model

### PR DESCRIPTION
**Pull request by SpencerLong0624**
I finished the predict route to be able to handle our newly trained ML model. In the predict function, I added validations to ensure that the input parameters are within the range of our dataset. I also updated the Swagger docs to reflect our changes. New test functions were added in the test suite in order to account for edge cases that we previously did not account for.

### CODE REVIEW

**Comment by SpencerLong0624** [comment]
Resolves #11

**Comment by SpencerLong0624** [comment]
Resolves #10

**Review by jennnnn-z — APPROVED** [review]
lgtm

**Review by YiHanna — APPROVED** [review]
Looks good to me

**Pull request merged**
